### PR TITLE
Fixes #20 skip checking of flags for unknown mechs

### LINKED ISSUE #20: The EnumerateMechanisms test fails with vendor defined / unknown mechs
The PKCS#11 library I'm testing with (nCipher PKCS#11) supports a large number of vendor-defined mechs.

The EnumerateMechanisms test wrongly checks these mechs for unexpected mech flags and fails.

If a mech is unknown to the test suite we should skip checking it's allowed flags values.

### PR DESCRIPTION
**Pull request by inorton**
This change skips checking of allowed mechanism flags for mechanisms
that are not known to the test suite (such as vendor defined mechs).

It also adds:
  CKM_SHA224_RSA_PKCS_PSS
  CKM_SHA224_HMAC_GENERAL
  CKM_SHA224_HMAC
  CKM_SHA224
  CKM_AES_ECB
  CKM_DES_ECB
  CKM_DES3_ECB

To the known mechs list in globals.cc

### CODE REVIEW

File: globals.cc [hunk 1]
```diff
@@ -137,6 +137,7 @@ std::set<CK_MECHANISM_TYPE> sign_verify_mechanisms = {
   CKM_RIPEMD128_RSA_PKCS,
   CKM_RIPEMD160_RSA_PKCS,
   CKM_SHA1_RSA_PKCS_PSS,
+  CKM_SHA224_RSA_PKCS_PSS,
```
Comment (daviddrysdale) [inline globals.cc]: Should `CKM_SHA224_RSA_PKCS` also be added slightly further up?  ([Table 80 of v2.40 Current Mechanisms](http://docs.oasis-open.org/pkcs11/pkcs11-curr/v2.40/errata01/os/pkcs11-curr-v2.40-errata01-os-complete.html#_Toc441850545) has it as Sign/Verify).

File: globals.cc [hunk 2]
```diff
@@ -307,8 +311,11 @@ std::set<CK_MECHANISM_TYPE> derive_mechanisms = {
   CKM_X9_42_DH_HYBRID_DERIVE,
   CKM_X9_42_MQV_DERIVE,
   CKM_KEA_KEY_DERIVE,
+  CKM_AES_ECB,
```
Comment (daviddrysdale) [inline globals.cc]: [Table 46 of v2.40 Current Mechanisms](http://docs.oasis-open.org/pkcs11/pkcs11-curr/v2.40/errata01/os/pkcs11-curr-v2.40-errata01-os-complete.html#_Toc441850484) just has Encrypt/Decrypt + Wrap/Unwrap for `CKM_AES_ECB` &ndash; am I missing a spec ref for Derive?

File: globals.cc [hunk 3]
```diff
@@ -307,8 +311,11 @@ std::set<CK_MECHANISM_TYPE> derive_mechanisms = {
...
+  CKM_DES_ECB,
```
Comment (daviddrysdale) [inline globals.cc]: Table 24 of [v2.20](https://www.cryptsoft.com/pkcs11doc/STANDARD/pkcs-11v2-20.pdf) just has Encrypt/Decrypt + Wrap/Unwrap for `CKM_DES_ECB` &ndash; is there an updated spec ref with Derive?

File: globals.cc [hunk 4]
```diff
@@ -307,8 +311,11 @@ std::set<CK_MECHANISM_TYPE> derive_mechanisms = {
...
   CKM_DES_ECB_ENCRYPT_DATA,
   CKM_DES_CBC_ENCRYPT_DATA,
+  CKM_DES3_ECB,
```
Comment (daviddrysdale) [inline globals.cc]: [Table 68 of v2.40 Current Mechanisms](http://docs.oasis-open.org/pkcs11/pkcs11-curr/v2.40/errata01/os/pkcs11-curr-v2.40-errata01-os-complete.html#_Toc441850525) just has Encrypt/Decrypt + Wrap/Unwrap for `CKM_DES3_ECB` (rather than `CKM_DES3_ECB_ENCRYPT_DATA`)?

File: globals.cc (hunk 1 above)
Comment (inorton) [reply globals.cc]: That might be a good idea

File: globals.cc (hunk 2 above)
Comment (inorton) [reply globals.cc]: Oh that is curious.. let me check if my library is not accidentally adding this beyond the spec

File: globals.cc (hunk 3 above)
Comment (inorton) [reply globals.cc]: As above I think you are correct that I've mistakenly added this.

File: globals.cc (hunk 4 above)
Comment (inorton) [reply globals.cc]: Yes that looks like it, my library is advertising it by mistake. Thanks! I will do a new commit shortly that cleans up

File: globals.cc (hunk 3 above)
Comment (inorton) [reply globals.cc]: Hmm actually, the draft v3 spec does include wrap/unwrap for CKM_AES_ECB, CKM_DES3_ECB (but not CKM_DES_ECB)

https://docs.oasis-open.org/pkcs11/pkcs11-curr/v3.0/pkcs11-curr-v3.0.html

Comment (daviddrysdale) [reply globals.cc]: Isn't this the Derive section though?

**Comment by inorton** [comment]
I've updated this to only include the fix for unknown mechs

**Review by daviddrysdale — APPROVED** [review]
